name: Pull Request

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - name: Shellcheck
        run: docker compose run --rm shellcheck build.sh

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
        with:
          submodules: recursive
      - name: Patch Dockerfile
        run: ./build.sh
      - name: Build
        uses: docker/build-push-action@v4.2.1
        with:
          context: .
