name: Push to main

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Shellcheck
        run: docker compose run --rm shellcheck build.sh

  build-push:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.4.0
        with:
          submodules: recursive
      - name: Patch Dockerfile
        run: ./build.sh
      - name: Login to Docker
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@v3.3.1
        with:
          context: .
          push: true
          tags: |
            technowledgy/postgres:14-alpine
            technowledgy/postgres:latest